
name: Documentation

on:
  pull_request:
    branches: [ master ]

jobs:
  cmake-formatting:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
    - name: Build documentation
      run: |
        set +e
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
        git clone https://github.com/dyninst/examples
        make html